version: '3'

networks:
  hadoop-net:

services:
  kerberos:
    build:
      context: .
      dockerfile: Dockerfile-kerberos
    volumes:
      - ./data/kerberos/keys:/data/keys
      - ./data/kerberos/db:/kdc/db
    expose:
      - "88"
      - "749"
    networks:
      - hadoop-net

  namenode:
    build:
      context: .
      dockerfile: Dockerfile-hadoop
    environment:
      - NODE_TYPE=name_node
    volumes:
      - ./data/hadoop/namenode:/data/namenode
    ports:
      - "50070:50070"
    expose:
      - "8020"
    networks:
      - hadoop-net
    depends_on:
      - kerberos

  datanode:
    build:
      context: .
      dockerfile: Dockerfile-hadoop
    environment:
      - NODE_TYPE=data_node
    volumes:
      - ./data/hadoop/datanode:/data/datanode
    ports:
      - "10025:10025"
    expose:
      - "10024"
    networks:
      - hadoop-net
    depends_on:
      - namenode

  resourcemanager:
    build:
      context: .
      dockerfile: Dockerfile-hadoop
    environment:
      - NODE_TYPE=resource_manager
    ports:
      - "8088:8088"
    expose:
      - "8082"
    networks:
      - hadoop-net
    depends_on:
      - namenode

  nodemanager:
    build:
      context: .
      dockerfile: Dockerfile-hadoop
    environment:
      - NODE_TYPE=node_manager
    ports:
      - "8042:8042"
    networks:
      - hadoop-net
    depends_on:
      - resourcemanager