version: '3'

networks:
  hadoop-net:

services:
  kerberos:
    hostname: kerberos
    build:
      context: .
      dockerfile: Dockerfile-kerberos
    volumes:
      - ./data/kerberos/keys:/data/keys
      - ./data/kerberos/db:/kdc/db
    expose:
      - "88"
      - "749"
    networks:
      - hadoop-net

  spark:
    build:
      context: .
      dockerfile: Dockerfile-spark
    networks:
      - hadoop-net
  
  namenode:
    hostname: namenode
    build:
      context: .
      dockerfile: Dockerfile-hadoop
    environment:
      - NODE_TYPE=name_node
    volumes:
      - ./data/ssl:/ssl
      - ./data/hadoop/namenode:/data/namenode
    ports:
      - "5001:5001"
    expose:
      - "8020"
    networks:
      - hadoop-net
    depends_on:
      - kerberos

  datanode:
    hostname: datanode
    build:
      context: .
      dockerfile: Dockerfile-hadoop
    environment:
      - NODE_TYPE=data_node
    volumes:
      - ./data/ssl:/ssl
      - ./data/hadoop/datanode:/data/datanode
    ports:
      - "5000:5000"
    networks:
      - hadoop-net
    depends_on:
      - namenode

  resourcemanager:
    hostname: resourcemanager
    build:
      context: .
      dockerfile: Dockerfile-hadoop
    environment:
      - NODE_TYPE=resource_manager
    volumes:
      - ./data/ssl:/ssl
    ports:
      - "5002:5002"
    networks:
      - hadoop-net
    depends_on:
      - namenode

  nodemanager:
    hostname: nodemanager
    build:
      context: .
      dockerfile: Dockerfile-hadoop
    environment:
      - NODE_TYPE=node_manager
    volumes:
      - ./data/ssl:/ssl
    ports:
      - "5003:5003"
    networks:
      - hadoop-net
    depends_on:
      - resourcemanager