FROM ubuntu:latest

RUN apt-get update && \
    apt-get install -y krb5-kdc krb5-admin-server

COPY ./kerberos/config/krb5.conf /etc/krb5.conf
COPY ./kerberos/config/kdc.conf /etc/krb5kdc/kdc.conf
COPY ./kerberos/config/kadm5.acl /etc/krb5kdc/kadm5.acl
COPY ./kerberos/scripts/* /scripts/

RUN chmod +x /scripts/*

ENV KRB5_CONFIG /etc/krb5.conf
ENV KRB5_KDC_PROFILE /etc/krb5kdc/kdc.conf

ENTRYPOINT ["/scripts/start_kdc.sh"]