version: '3'

networks:
  hadoop-net:

services:
  kerberos:
    build:
      context: ./kerberos
    networks:
      - hadoop-net

  namenode:
    build:
      context: ./hadoop
    environment:
      - NODE_TYPE=name_node
    volumes:
      - ./data/namenode:/data/namenode
    ports:
      - "50070:50070"
    expose:
      - "8020"
    networks:
      - hadoop-net
    depends_on:
      - kerberos

  datanode:
    build:
      context: ./hadoop
    environment:
      - NODE_TYPE=data_node
    volumes:
      - ./data/datanode:/data/datanode
    ports:
      - "9864:9864"
    networks:
      - hadoop-net
    depends_on:
      - namenode

  resourcemanager:
    build:
      context: ./hadoop
    environment:
      - NODE_TYPE=resource_manager
    ports:
      - "8088:8088"
    expose:
      - "8082"
    networks:
      - hadoop-net
    depends_on:
      - namenode

  nodemanager:
    build:
      context: ./hadoop
    environment:
      - NODE_TYPE=node_manager
    ports:
      - "8042:8042"
    networks:
      - hadoop-net
    depends_on:
      - resourcemanager